### ISSUE TITLE
Version 1.1.2 on NPM without the newest changes

### ISSUE THREAD

**Issue by lukaszwnek** [zhaluza/react-detect-click-outside#15]
Hello, first of all - thanks for implementing a great library!

I noticed that the newest version of the NPM package (1.1.2 as of the time of writing this) doesn't have the newest additions that can be seen on GitHub. Specifically, changes from this PR: https://github.com/zhaluza/react-detect-click-outside/pull/10.

In the compiled code in the `dist` folder, I can still see the dependencies array of the `useEffect` being empty:

<img width="853" alt="Screenshot 2022-03-17 at 13 54 55" src="https://user-images.githubusercontent.com/913786/158812849-5d73487b-1069-44ee-9400-a20b006a3cc6.png">

Would it be possible to re-publish it or publish a new version of the package?

Thanks a lot and have an awesome day!

**Comment by zhaluza** [comment]
Thanks @lukaszwnek , I've gone ahead and published the most up-to-date version. I'm closing this issue - if you notice any code that isn't appearing in the newest version, let me know!
